management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,prometheus
  endpoint:
    health:
      show-details: when-authorized
  tracing:
    sampling:
      probability: 1.0

spring:
  jackson:
    default-property-inclusion: non_null
