eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

infra:
  postgres:
    host: localhost
    port: 5432
  redis:
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: localhost:9094
  s3:
    region: ${AWS_REGION:eu-central-1}
    access-key: ${AWS_ACCESS_KEY_ID:}
    secret-key: ${AWS_SECRET_ACCESS_KEY:}
    bucket: ${S3_BUCKET:park-spot}

parkspot:
  web-origin: http://localhost:4200

management:
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
